# Change these first
owner: ngc7331 # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Orange
    url: https://isorangealive.ngc7331.site
  - name: Black
    url: https://isblackalive.ngc7331.top:4443
  - name: Red
    url: $SECRET_SITE_1
  - name: Onedrive(Microsoft)
    url: $SECRET_SITE_2

assignees: # Users to assign downtime issues (optional)
  - ngc7331

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: upptime.ngc7331.top
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ngc7331/upptime/master/icon.png
  name: xu_zh的服务器还活着吗？
  introTitle: "欢迎来到xu\_zh的辣鸡服务器"
  introMessage: "本页面基于开源软件[**Upptime**](https://github.com/koj-co/upptime)和Github Action，其作用是监控本站服务是否正常运行。Black为阿里云公网服务器，包含Blog、Nextcloud、Oneindex等服务。Onedrive为由微软提供的后端服务，如果您无法从Oneindex上下载文件则多半是该服务出现问题。Red为内网测试服务器，本页面到它的链接需要经过Black中继，即当Black和Red同时离线时Red可能仍在正常运行"
  navbar:
    #- title: Status
    #  href: /
    - title: My Blog
      href: https://ngc7331.top:4443
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# 汉化(Translated to Chinese by xu_zh)
i18n:
  activeIncidents: 活跃事件
  allSystemsOperational: 所有服务运行正常
  incidentReport: "事件 #$NUMBER 报告 →"
  activeIncidentSummary: 于 $DATE 开始，已有$POSTS次状态更新
  incidentTitle: 事件 $NUMBER 详情
  incidentDetails: 事件详情
  incidentFixed: 已恢复
  incidentOngoing: 进行中
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentSubscribe: 订阅更新
  incidentViewOnGitHub: 在GitHub上查看
  incidentCommentSummary: 由 $AUTHOR 于 $DATE 发布
  incidentBack: ← 返回列表
  pastIncidents: 历史事件
  pastIncidentsResolved: 在 $MINUTES 分钟内经过$POSTS次更新恢复
  liveStatus: 实时状态
  overallUptime: "可用性: $UPTIME"
  overallUptimeTitle: 可用性
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: 平均响应时间
  sevelDayResponseTime: 7日响应时间图表
  responseTimeMs: 响应时间 (ms)
  up: 在线
  down: 离线
  degraded: 已降级
  ms: ms
  loading: 载入中
  navGitHub: GitHub
  footer: "本页面是 [开源软件]($REPO), 由 [Upptime](https://upptime.js.org) 出品, 由 [xu\_zh](https://github.com/ngc7331) 翻译"
  rateLimitExceededTitle: 达到请求数上限
  rateLimitExceededIntro: 你已达到本小时的请求数上限，因此你需要等待一段时间才能再次访问。你也可以添加一个GitHub个人访问令牌(Personal Access Token)来继续使用本页面。
  rateLimitExceededWhatDoesErrorMean: 这个错误意味着什么？
  rateLimitExceededErrorMeaning: 本页面使用了GitHub API来获得这些服务的实时状态。GitHub一般允许每个IP地址每小时发出60次请求，你已达到该上限。
  rateLimitExceededErrorHowCanFix: 如何修复该错误？
  rateLimitExceededErrorFix: 你可以稍等一个小时来自动恢复你的IP地址访问限制。你也可以添加你的GitHub个人访问令牌(Personal Access Token)，这会允许你每小时额外发出5000次请求。
  rateLimitExceededGeneratePAT: 学习如何生成个人访问令牌(Personal Access Token)
  rateLimitExceededHasSet: 你已设置个人访问令牌(Personal Access Token)
  rateLimitExceededRemoveToken: 移除令牌
  rateLimitExceededGitHubPAT: GitHub个人访问令牌(Personal Access Token)
  rateLimitExceededCopyPastePAT: 复制并粘贴你的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 发生错误
  errorIntro: 尝试获取最新状态时发生错误
  errorText: 请稍后再试
  errorHome: 返回主页
